#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Set keyboard layout
setxkbmap -layout us -variant altgr-intl

# Invert trackpad scroll
xinput set-button-map 14 1 2 3 5 4

# XComposite
xcompmgr &

# Set default cursor
xsetroot -cursor_name center_ptr

# Disable touchpad while typing
syndaemon -i 1 -d

# Launch media keys Listener
~/.media_handler &

# Set wallpaper
~/.fehbg

# Run XScreenSaver in the background
xscreensaver &

# Trayer
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
       --expand true --width 5 --transparent true --tint 0x191970 --height 25 &


# Merge in defaults and keymaps
[ -f $sysresources ] && /usr/bin/xrdb -merge $sysresources
[ -f $sysmodmap ] && /usr/bin/xmodmap $sysmodmap
[ -f $userresources ] && /usr/bin/xrdb -merge $userresources
[ -f $usermodmap ] && /usr/bin/xmodmap $usermodmap

if [ -z "$DESKTOP_SESSION" -a -x /usr/bin/ck-launch-session ]; then
  exec ck-launch-session dbus-launch --exit-with-session /usr/bin/xmonad
else
  exec /usr/bin/xmonad
fi
