#!/bin/sh
case "$1" in
  "C-d")
    while read -r file
    do
      FILE_FULL_PATH=$(readlink -f "$file")
      nix run "nixpkgs#xorg.xmessage" -- -buttons ok:1,cancel:0 "Really delete $FILE_FULL_PATH?"
      exitStat=$?

      if $exitStat; then
        rm "$FILE_FULL_PATH"
      fi
    done
    ;;
  "C-w")
    while read -r file
    do
      FILE_FULL_PATH=$(readlink -f "$file")
      echo "Setting wallpaper:" "$FILE_FULL_PATH"
      feh --bg-center "$FILE_FULL_PATH"
      notify-send -i "$FILE_FULL_PATH" "Wallpaper changed"
    done
    ;;
esac
