# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  gitduck = nodeEnv.buildNodePackage {
    name = "gitduck";
    packageName = "gitduck";
    version = "0.0.9";
    src = fetchurl {
      url = "https://registry.npmjs.org/gitduck/-/gitduck-0.0.9.tgz";
      sha512 = "hk2RpHa1tk9I7nYkt90tqrvoxnfGqyFzIK0fKhdjHURfOZ2F+A31WioC1f/aoX6eP+Vp6xPJS56z++6InBBxzQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Share your terminal on a GitDuck video call";
      homepage = "https://gitduck.com";
      license = "Custom";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
