# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  gitduck = nodeEnv.buildNodePackage {
    name = "gitduck";
    packageName = "gitduck";
    version = "0.0.7";
    src = fetchurl {
      url = "https://registry.npmjs.org/gitduck/-/gitduck-0.0.7.tgz";
      sha512 = "W8zrrCQe2997bRrLknUeRR118qQk5/tgITKBgq1V2xYy4bP9r9sc5x9+vhkOCx79p7KUXC72pARfiNFFdsjkHA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Share your terminal on a GitDuck video call";
      homepage = https://gitduck.com/;
      license = "Custom";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}